import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// <body className={inter.className}>{children}</body> came right after <html lang="en"> below

export default function RootLayout({ children }) {
  
  return (
    <html lang="en">
      <body>
        <nav>
          <ul className="flex justify-center space-x-4">
            <li><a href="/" className="hover:bg-violet-600">About Me</a></li>
            <li><a href="/education" className="hover:bg-violet-600">Education</a></li>
            <li><a href="/work-experience" className="hover:bg-violet-600">Work Experience</a></li>
            <li><a href="/projects" className="hover:bg-violet-600">Projects</a></li>
            <li><a href="/test">TEST PAGE</a></li>
          </ul>
        </nav>
        <main>{children}</main>
      </body>
    </html>
  );
}
